pr:
  branches:
    include:
      - dev
  paths:
    exclude:
      - docs/*
      - README.md

trigger:
 branches:
   include:
     - master
 paths:
   exclude:
     - docs/*
     - README.md
     - 01_azure-pipelines-ci.yml
     - 02_azure-pipelines-ci.yml
     - 03_azure-pipelines-ci-cd.yml
agents:
  - name: ADO
parameters:
- name: runCompletePipeline
  displayName: Run All Tasks ?
  type: boolean
  default: true

stages:
- stage: Build_Stage
  displayName: Build Apps
  jobs:

  - job: WebApp
    displayName: Build Web App
    pool:
      name: Hosted Windows 2019 with VS2019 
      vmImage: 'windows-latest'
    variables:
      BuildConfiguration: release
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: UseDotNet@2
      displayName: Install .NET 6 sdk
      inputs:
        packageType: sdk
        version: 6.0.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: DotNetCoreCLI@2
      displayName: Restore Nuget Packages
      inputs:
        command: restore
        projects: '**/WebApp.csproj'
