trigger:
- main

stages:
  - stage: Build
    jobs:
      - job: Build 
        pool:
          vmImage: 'windows-latest'
        steps:
          # Install npm packages
          - task: Npm@1
            inputs:
              command: 'install'
          
          # Run the custom build command
          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run build'
          
          # Publish build artifacts
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'build'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Deploy
    jobs:
      - job: Deploy
        pool:
          name: 'Default'  # Replace 'Default' with your custom agent pool name
        steps:
          # Download build artifacts
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          # Deploying to the local machine
          - script: |
              echo "Deploying to local machine"
              if not exist "D:\ADO\SampleProject" mkdir "D:\ADO\SampleProject"
              xcopy /E /I "$(System.ArtifactsDirectory)\drop\*" "D:\ADO\SampleProject\"
            displayName: 'Deploy to Local Machine'
